# Generated by Django 6.0.7 on 2026-07-24 10:20

import Base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(storage=Base.models.RawMediaCloudinaryStorage(), upload_to='resumes/'),
        ),
    ]
