# Generated by Django 6.0.7 on 2026-07-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_blogpost'),
    ]

    operations = [
    ]
